# Generated by Django 4.2.20 on 2025-04-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.CharField(default=listings.models.generate_identifier, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('in_circulation', 'In Circulation'), ('being_repaired', 'Being Repaired')], default='checked_in', max_length=20)),
                ('location', models.CharField(help_text='e.g., home library, work library', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('views', models.PositiveIntegerField(default=0)),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loras', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_loras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('image', models.ImageField(blank=True, default='collections/default_collection_image.jpg', null=True, upload_to=listings.models.model_image_upload)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_models', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_models', to=settings.AUTH_USER_MODEL)),
                ('loras', models.ManyToManyField(blank=True, related_name='models', to='listings.lora')),
            ],
        ),
        migrations.CreateModel(
            name='LoRARating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='listings.lora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lora_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoRAImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='items/default_item_image.png', upload_to=listings.models.lora_image_upload)),
                ('lora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.lora')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('lora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.lora')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_comments', to='listings.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
