# Generated by Django 4.2.18 on 2025-03-14 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        # Example: remove default altogether (you can allow null if needed first)
        migrations.AddField(
            model_name='listing',
            name='librarian',
            field=models.ForeignKey(
                null=True,  # temporary allow null if needed for existing data
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='listings',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
