# Generated by Django 4.2.20 on 2025-04-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
    ]
