# Generated by Django 4.2.18 on 2025-03-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_item_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='listings.collection')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
