# Generated by Django 4.2.18 on 2025-03-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_collectionaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionAccess',
        ),
    ]
