# Generated by Django 4.2.18 on 2025-03-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_delete_collectionaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='items/default_item_image.png', null=True, upload_to='items/'),
        ),
    ]
