# Generated by Django 4.2.20 on 2025-04-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='uploaded_at',
        ),
    ]
