# Generated by Django 4.2.18 on 2025-04-08 23:40

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_item_image_remove_itemimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='collections/default_collection_image.png', null=True, upload_to='collections/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='items/default_item_image.png', upload_to=listings.models.item_image_upload),
        ),
    ]
