# Generated by Django 4.2.18 on 2025-04-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_collection_image_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='collections/default_collection_image.jpg', null=True, upload_to='collections/'),
        ),
    ]
