# Generated by Django 4.2.18 on 2025-04-08 23:57

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='collections/default_collection_image.jpg', null=True, upload_to=listings.models.collection_image_upload),
        ),
    ]
