# Generated by Django 4.2.18 on 2025-03-15 19:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to=accounts.models.profile_image_upload),
        ),
    ]
