# Generated by Django 4.2.20 on 2025-04-28 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
