# Generated by Django 4.2.20 on 2025-04-12 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_auto_20250412_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_new', to='listings.model')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='Exact borrowing duration (e.g., 1 day, 2:30:00)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='listings.lora')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedLoRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(help_text="Duration (e.g., '1 day, 2:30:00' for 1 day, 2 hours, and 30 minutes)")),
                ('reminder_sent', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_lora', to='patron_requests.borrowrequest')),
                ('lora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_instances', to='listings.lora')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
