# Generated by Django 4.2.18 on 2025-03-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionaccessrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='collectionaccessrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
