# Generated by Django 4.2.18 on 2025-03-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_requests', '0002_alter_collectionaccessrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaccessrequest',
            name='archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
